### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [DieZzZeL2021/Kinozal#1]
1)
ссылка не работает
![image](https://user-images.githubusercontent.com/8464662/121195105-ff9bdc00-c877-11eb-96e4-fc2087a7cd0b.png)

2)
вторая страница не создана

3)
у вас отступы 6 пробелов, допускается 2 или 4 но одинаково для html css и js
![image](https://user-images.githubusercontent.com/8464662/121195338-2f4ae400-c878-11eb-9d3b-e52d98901e86.png)

4)
что делают лишние пробелы?
![image](https://user-images.githubusercontent.com/8464662/121195469-4be71c00-c878-11eb-920b-af4eec35ce9c.png)

**Comment by AnatoliySysoenko** [comment]
Добрый день, Андрей подскажите, пожалуйста как выйти из ситуации. У меня
много лишних пробелов в проекте кинозал, вы выше указали мне на это, но как
я не пробовал их убрать, при Control+S, они сами автоматически становяться
обратно

вт, 8 июн. 2021 г. в 16:42, Andrey ***@***.***>:

**Comment by AnatoliySysoenko** [comment]
Я так понимаю что это делает расширение какое то, но что то полазил и не
могу найти

ср, 16 июн. 2021 г. в 12:40, Анатолий Сысоенко ***@***.***>:

**Comment by AnatoliySysoenko** [comment]
https://diezzzel2021.github.io/Kinozal/
https://github.com/DieZzZeL2021/Kinozal

Сделал страницу page и оформил, также пофиксил пробелы

ср, 16 июн. 2021 г. в 12:48, Анатолий Сысоенко ***@***.***>:

**Comment by Alecto** [comment]
установите количество пробелов по умолчанию и исправьте количество пробелов
для всех документов.
решение гуглится, решение есть в уроке по настройке вскод

ср, 16 июн. 2021 г. в 12:41, DieZzZeL2021 ***@***.***>:

**Comment by AnatoliySysoenko** [comment]
Вроде настроил вс код и пофиксил пробелы. Я не знаю, посмотрите правильно
ли)
А в остальном правильно?
https://diezzzel2021.github.io/Kinozal/
https://github.com/DieZzZeL2021/Kinozal

ср, 16 июн. 2021 г. в 18:22, Andrey ***@***.***>:

**Comment by Alecto** [comment]
да, теперь похоже на правду.
оценку кому ставить?
в переписке потерялось

**Comment by AnatoliySysoenko** [comment]
Сысоенко Анатолий)))) FE2104 (сб/вс 9:30)

чт, 17 июн. 2021 г. в 12:42, Andrey ***@***.***>:

**Comment by Alecto** [comment]
спасибо.
отметил

>
